FROM python:3.8.6-slim-buster as downloader
ARG VERSION=202112.05

LABEL container.base.image="python:3.8.6-slim-buster" \
      software.version="${VERSION}" \
      software.website="https://www.sentieon.com/"

# Download the software from the permalink
RUN apt-get update && apt-get install -y wget bzip2 build-essential 
RUN apt-get install -y zlib1g-dev
RUN mkdir -p /opt/sentieon/ && \
    wget -nv -O - "https://s3.amazonaws.com/sentieon-release/software/sentieon-genomics-${VERSION}.tar.gz" | \
      tar -zxf - -C /opt/sentieon/
RUN mkdir -p /opt/bcftools/ && \
    wget -nv -O - "https://github.com/samtools/bcftools/releases/download/1.14/bcftools-1.14.tar.bz2" | \
      tar -jxf - -C /opt/bcftools/ --no-same-owner && \
      cd /opt/bcftools/bcftools-1.14/ && \
      ./configure --disable-bz2 --disable-lzma && make && make install

# Build the container
FROM python:3.8.6-slim-buster
ARG VERSION=202112.05

COPY --from=downloader /opt/sentieon/sentieon-genomics-${VERSION} /opt/sentieon/sentieon-genomics-${VERSION}
COPY --from=downloader /usr/local/bin/* /usr/local/bin/
COPY --from=downloader /usr/local/libexec/bcftools/* /usr/local/libexec/bcftools/
COPY bnd_to_insdel.py /opt/bnd_to_insdel.py
RUN python -m pip install --upgrade pip && \
    pip install pyfaidx 

ENV PATH /opt/sentieon/sentieon-genomics-${VERSION}/bin/:$PATH
